#!/usr/bin/python

import rospy

import smach
import smach_ros
from cart_collection.cart_collection_states import GetCartPose, LookForCart, GetSetpointInPreDockArea, GoToPreDockSetpoint, AlignAndApproachCart, CoupleToCart, GetSetpointInPostDockArea, GoToPostDockSetpoint

def main():
    rospy.init_node('cart_collection')
    SM = smach.StateMachine(outcomes=['done', 'failed'])
    SM.userdata.docking_area = '60' #61 = next to C025; 60 = next to C022
    SM.userdata.cart_pose = None
    SM.userdata.pre_dock_setpoint = None
    SM.userdata.post_dock_setpoint  = None

    with SM:
        smach.StateMachine.add('GET_CART_POSE', GetCartPose(),
            transitions={'cart_found': 'GET_SETPOINT_IN_PRE_DOCK_AREA',
                         'cart_not_found': 'LOOK_FOR_CART',
                         'timeout': 'failed'})

        smach.StateMachine.add('LOOK_FOR_CART', LookForCart(),
            transitions={'cart_found': 'GET_SETPOINT_IN_PRE_DOCK_AREA',
                         'cart_not_found': 'failed',
                         'timeout': 'failed'})

        smach.StateMachine.add('GET_SETPOINT_IN_PRE_DOCK_AREA', GetSetpointInPreDockArea(),
            transitions={'setpoint_found': 'GO_TO_PRE_DOCK_SETPOINT',
                         'setpoint_unreachable': 'failed'})

        smach.StateMachine.add('GO_TO_PRE_DOCK_SETPOINT', GoToPreDockSetpoint(),
            transitions={'reached_setpoint': 'ALIGN_AND_APPROACH_CART',
                         'setpoint_unreachable': 'failed',
                         'timeout': 'failed'})

        smach.StateMachine.add('ALIGN_AND_APPROACH_CART', AlignAndApproachCart(),
            transitions={'approach_succeeded': 'COUPLE_TO_CART',
                         'cart_not_found': 'GET_CART_POSE',
                         'timeout': 'GO_TO_PRE_DOCK_SETPOINT'})

        smach.StateMachine.add('COUPLE_TO_CART', CoupleToCart(),
            transitions={'coupling_succeeded': 'GET_SETPOINT_IN_POST_DOCK_AREA',
                         'coupling_failed': 'GO_TO_PRE_DOCK_SETPOINT',
                         'cannot_switch_to_load_mode': 'failed'})

        smach.StateMachine.add('GET_SETPOINT_IN_POST_DOCK_AREA', GetSetpointInPostDockArea(),
            transitions={'setpoint_found': 'GO_TO_POST_DOCK_SETPOINT',
                         'setpoint_unreachable': 'done'})

        smach.StateMachine.add('GO_TO_POST_DOCK_SETPOINT', GoToPostDockSetpoint(),
            transitions={'reached_setpoint': 'done',
                         'setpoint_unreachable': 'done',
                         'timeout': 'done'})
    result = SM.execute()
    while (result is None):
        rospy.spin()

if __name__ == '__main__':
    main()
